--liquibase formatted sql
--changeset kkwwaa:001

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_id BIGINT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    sex VARCHAR(50),
    parent_name VARCHAR(255),
    phone VARCHAR(50),
    anamnesis TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (specialist_id) REFERENCES users(id)
);

CREATE TABLE protocols (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE probes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    instruction TEXT
);

CREATE TABLE protocol_probes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    protocol_id BIGINT NOT NULL,
    probe_id BIGINT NOT NULL,
    sort_order BIGINT NOT NULL,
    FOREIGN KEY (protocol_id) REFERENCES protocols(id),
    FOREIGN KEY (probe_id) REFERENCES probes(id),
    UNIQUE (protocol_id, probe_id)
);

CREATE TABLE modalities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    value_type VARCHAR(50) NOT NULL,
    direction VARCHAR(50) NOT NULL,
    min_value FLOAT,
    max_value FLOAT,
    weight FLOAT DEFAULT 1.0 NOT NULL
);

CREATE TABLE modality_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_id BIGINT NOT NULL,
    modality_id BIGINT NOT NULL,
    weight FLOAT DEFAULT 1.0 NOT NULL,
    FOREIGN KEY (parameter_id) REFERENCES parameters(id),
    FOREIGN KEY (modality_id) REFERENCES modalities(id),
    UNIQUE (parameter_id, modality_id)
);

CREATE TABLE probe_parameters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    probe_id BIGINT NOT NULL,
    parameter_id BIGINT NOT NULL,
    FOREIGN KEY (probe_id) REFERENCES probes(id),
    FOREIGN KEY (parameter_id) REFERENCES parameters(id),
    UNIQUE (probe_id, parameter_id)
);

CREATE TABLE parameter_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parameter_id BIGINT NOT NULL,
    value VARCHAR(255) NOT NULL,
    score FLOAT NOT NULL,
    sort_order BIGINT NOT NULL,
    FOREIGN KEY (parameter_id) REFERENCES parameters(id)
);

CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    protocol_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    examination_date DATE NOT NULL,
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (protocol_id) REFERENCES protocols(id)
);

CREATE TABLE session_probes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    probe_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    note TEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    FOREIGN KEY (probe_id) REFERENCES probes(id),
    UNIQUE (session_id, probe_id)
);

CREATE TABLE responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_probe_id BIGINT NOT NULL,
    parameter_id BIGINT NOT NULL,
    numeric_value FLOAT,
    option_id BIGINT,
    FOREIGN KEY (session_probe_id) REFERENCES session_probes(id),
    FOREIGN KEY (parameter_id) REFERENCES parameters(id),
    FOREIGN KEY (option_id) REFERENCES parameter_options(id),
    UNIQUE (session_probe_id, parameter_id),
    CHECK (
        (numeric_value IS NOT NULL AND option_id IS NULL)
        OR
        (numeric_value IS NULL AND option_id IS NOT NULL)
    )
);

CREATE TABLE results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    modality_id BIGINT NOT NULL,
    score FLOAT NOT NULL,
    grade VARCHAR(50) NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    FOREIGN KEY (modality_id) REFERENCES modalities(id),
    UNIQUE (session_id, modality_id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    ai_draft TEXT,
    final_text TEXT,
    status VARCHAR(50) NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(id),
    UNIQUE (session_id)
);
